version: "3.8"
networks: 
  traefik-net:
    external: true
  home-net:
    driver: overlay
services:
# qBittorrent
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    #container_name: qbittorrent2
    networks: 
      - traefik-net
      - home-net
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - WEBUI_PORT=8580
    dns:
      - ${DNS_1}
      - ${DNS_2}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /data/qbittorrent:/config
      - /Volumes/deadpool-5/qbittorrent:/downloads
      - /Volumes:/Volumes
    ports:
      - "8580:8580"
      - "6882:6881"
      - "6882:6881/udp"
    #restart: "unless-stopped"
    deploy:
      #mode: global
      replicas: 1
      placement:
        max_replicas_per_node: 2
        #constraints: [node.role == manager]
        constraints: [node.platform.os == linux]
      restart_policy:
        condition: any
        delay: 30s
        max_attempts: 20
        window: 300s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.qbittorrent.rule=Host(`qbittorrent.caffeen.lan`)"
      - "traefik.http.routers.qbittorrent.entrypoints=web"
      - "traefik.http.services.qbittorrent.loadbalancer.server.port=8580"
  ## NZB Get
  nzbget:
    image: lscr.io/linuxserver/nzbget:latest
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - NZBGET_USER=nzbget #optional
      - NZBGET_PASS=tegbzn6789 #optional
    networks: 
      - home-net

    dns:
      - ${DNS_1}
      - ${DNS_2}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /data/nzbget:/config
      - /Volumes:/Volumes
    ports:
      - "6790:6790"
    #restart: "no"
    deploy:
      #mode: global
      replicas: 1
      placement:
        max_replicas_per_node: 2
        #constraints: [node.role == manager]
        constraints: [node.platform.os == linux]
      restart_policy:
        condition: any
        delay: 30s
        max_attempts: 20
        window: 300s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nzbget.rule=Host(`nzbget.caffeen.lan`)"
      - "traefik.http.routers.nzbget.entrypoints=web"
      - "traefik.http.services.nzbget.loadbalancer.server.port=6790"  
